In [14]:
# Basics of Neural Network - Deep Learning
# Activation Functions, Bias, Weights, Inputs
# Look Up Terms like - Forward Propagation, Back Propagation, Hidden Layer, etc


import numpy as np

In [15]:
# We are using maximum - Maths : Probability, Statistics, Arithmetic, Trignometry, Calculus, Derivatives (for like function tanh)

In [16]:
# pip install tensorflow

In [17]:
# pip install torch

In [18]:
# Softmax Function
def soft(x):
    return np.exp(x)/np.sum(np.exp(x))

In [19]:
x = np.array([2,2.2,2.8,3,3.4,3.9,4,4.3])

In [20]:
output = soft(x)

In [21]:
output


array([0.02835306, 0.03463051, 0.0631009 , 0.07707161, 0.11497734,
       0.18956558, 0.20950237, 0.28279862])

In [22]:
import torch
y = torch.tensor(x)
y

# to convert it to a vector

tensor([2.0000, 2.2000, 2.8000, 3.0000, 3.4000, 3.9000, 4.0000, 4.3000],
       dtype=torch.float64)

In [23]:
# tensor = difference between 2 vectors, eg., vector 1 and vector 2

In [24]:
out = torch.softmax(y, dim=0)
# has a built in softmax function
# softmax can help us work with multidimensions

In [26]:
out

tensor([0.0284, 0.0346, 0.0631, 0.0771, 0.1150, 0.1896, 0.2095, 0.2828],
       dtype=torch.float64)

In [27]:
torch.sigmoid(y)

tensor([0.8808, 0.9002, 0.9427, 0.9526, 0.9677, 0.9802, 0.9820, 0.9866],
       dtype=torch.float64)

In [28]:
torch.relu(y)

tensor([2.0000, 2.2000, 2.8000, 3.0000, 3.4000, 3.9000, 4.0000, 4.3000],
       dtype=torch.float64)

In [29]:
torch.tanh(y)

tensor([0.9640, 0.9757, 0.9926, 0.9951, 0.9978, 0.9992, 0.9993, 0.9996],
       dtype=torch.float64)

In [ ]:
# tensorflow is a library
# pytorch

In [ ]:
# easy to make activation functions in torch